const OPEN_CURLY_BRACE = "OPEN_CURLY_BRACE";
const CLOSE_CURLY_BRACE = "CLOSE_CURLY_BRACE";
const OPEN_PARENTHESES = "OPEN_PARENTHESES";
const CLOSE_PARENTHESES = "CLOSE_PARENTHESES";
const SEMICOLON = "SEMICOLON";
const INT_KEYWORD = "INT_KEYWORD";
const RETURN_KEYWORD = "RETURN_KEYWORD";
const IDENTIFIER = "IDENTIFIER";
const INTEGER_LITERAL = "INTEGER_LITERAL";
const EXPRESSION = "EXPRESSION";
const STATEMENT = "STATEMENT";
const FUNCTION_DECLARATION = "FUNCTION_DECLARATION";
const PROGRAM = "PROGRAM";

module.exports.OPEN_CURLY_BRACE = OPEN_CURLY_BRACE;
module.exports.CLOSE_CURLY_BRACE = CLOSE_CURLY_BRACE;
module.exports.OPEN_PARENTHESES = OPEN_PARENTHESES;
module.exports.CLOSE_PARENTHESES = CLOSE_PARENTHESES;
module.exports.SEMICOLON = SEMICOLON;
module.exports.INT_KEYWORD = INT_KEYWORD;
module.exports.RETURN_KEYWORD = RETURN_KEYWORD;
module.exports.IDENTIFIER = IDENTIFIER;
module.exports.INTEGER_LITERAL = INTEGER_LITERAL;
module.exports.EXPRESSION = EXPRESSION;
module.exports.STATEMENT = STATEMENT;
module.exports.FUNCTION_DECLARATION = FUNCTION_DECLARATION;
module.exports.PROGRAM = PROGRAM;

